apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: drone
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: rabbit-manage
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: rabbit
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: rabbit-fed
      port: 31001
      protocol: TCP
      targetPort: 31001
